name: SPA CI/CD

on:
  push:
    branches: [ main ]
  
jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Configure nodejs 14'
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: 'Archive e2e tests'
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r e2e-tests.zip cypress cypress.json
    - name: 'Upload e2e tests artifact'
      uses: actions/upload-artifact@v2
      with:
        name: e2e-tests.zip
        path: e2e-tests.zip
    - name: 'Login to the Azure Container Registry' 
      uses: azure/docker-login@v1
      with:
        login-server: dotnet2021cypress.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: 'Build the docker image and push it to the ACR' 
      run: |
        docker build . -t dotnet2021cypress.azurecr.io/spa:${{ github.sha }}
        docker push dotnet2021cypress.azurecr.io/spa:${{ github.sha }}

  CD:
    name: CD to Dev 
    needs: CI
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'https://dotnet2021-cypress.azurewebsites.net'
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy the docker image to the WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dotnet2021-cypress'
        images: 'dotnet2021cypress.azurecr.io/spa:${{ github.sha }}'
    - name: 'Azure logout'
      run: |
        az logout

  e2e:
    name: Run e2e tests
    needs: CD
    runs-on: ubuntu-latest
    steps:
    - name: 'Configure nodejs 14'
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: 'Install typescript locally'
      run: npm install typescript@^4.1.2
    - name: 'Download e2e tests artifact'
      uses: actions/download-artifact@v2
      with:
        name: e2e-tests.zip
    - name: 'Extract e2e tests'
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq e2e-tests.zip -d e2e-tests
    - name: 'Fix e2e tests folder permissions'
      run: sudo chmod -R 777 e2e-tests
    - name: 'Update cypress.json baseUrl'
      uses: jossef/action-set-json-field@v1
      with:
        file: ./e2e-tests/cypress.json
        field: baseUrl
        value: https://dotnet2021-cypress.azurewebsites.net
    - name: 'Run e2e tests with Cypress'
      run: npx cypress run
      working-directory: ./e2e-tests
    - name: 'Publish Test Results'
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ./e2e-tests/test-output-*.xml
