name: SPA CI/CD

on:
  push:
    branches: [ main ]
  
jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r e2e-tests.zip cypress cypress.json
    - uses: actions/upload-artifact@v2
      with:
        name: e2e-tests.zip
    - uses: azure/docker-login@v1
      with:
        login-server: dotnet2021cypress.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t dotnet2021cypress.azurecr.io/spa:${{ github.sha }}
        docker push dotnet2021cypress.azurecr.io/spa:${{ github.sha }}

  CD:
    name: CD to Dev 
    needs: CI
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'https://dotnet2021-cypress.azurewebsites.net'
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'dotnet2021-cypress'
        images: 'dotnet2021cypress.azurecr.io/spa:${{ github.sha }}'
    - name: Azure logout
      run: |
        az logout

  e2e:
    name: Run e2e tests
    needs: CD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: e2e-tests.zip
    - uses: montudor/action-zip@v1
      with:
        args: unzip -qq e2e-tests.zip -d e2e-tests
