name: SPA CI

on:
  push:
    branches: [ main ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: dotnet2021cypress.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t dotnet2021cypress.azurecr.io/spa:${{ github.sha }}
        docker push dotnet2021cypress.azurecr.io/spa:${{ github.sha }}
